main.yaml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,30 +1,38 @@
 name: Vanta Race - RePAK
 
 on: [push, pull_request, workflow_dispatch]
+
 jobs:
   json-lint:
     runs-on: ubuntu-20.04
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - name: Install Dependencies
         run: ( cd tests/json-syntax && npm install )
+
       - name: Run NPM Test
         run: ( cd tests/json-syntax && npm test )
+
+      - name: Check PR Description
+        env:
+          PRDESC: ${{ github.event.pull_request.body }}
+        run: |
+          echo "$PRDESC" | grep -qvz '"' || ( echo "::error:: PR Description should not contain double quote symbols [\"], use single quote ['] instead."; false )
 
   luacheck:
     runs-on: ubuntu-20.04
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - name: Install dependencies
         run: sudo apt-get install -y luarocks && sudo luarocks install luacheck
       - name: RUN -- luacheck .
         run: luacheck --no-color --quiet .
 
   check-unoptimized-png:
-    # if: ${{ github.base_ref || github.ref != 'refs/heads/master' }}
+    if: ${{ github.base_ref || github.ref != 'refs/heads/master' }}
     runs-on: ubuntu-20.04
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - name: Install Dependencies
         run: sudo apt-get install -y optipng
       - run: .github/scripts/check-png-images.sh
@@ -35,7 +43,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Remove unneeded paths & files in PAK file (i.e., ".git", ".disabled")
-        run: rm -rf .git .disabled tests
+        run: rm -rf .git .disabled tests .old bak
       - uses: edwardspec/github-action-pack-starbound-mod@v1
         with:
           outputFileName: vanta-race.pak
